# cloudbuild.yaml
# Ce fichier décrit les étapes de construction de l'image Docker

steps:
  # Étape 1: Construire l'image Docker
  # On utilise le builder Docker fourni par Google
- name: 'gcr.io/cloud-builders/docker'
  # On exécute la commande "docker build"
  # -t : pour tagger (nommer) l'image
  # .  : pour dire que le Dockerfile est dans le dossier courant
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cvmatcher-image:$COMMIT_SHA', '.']

# Une fois le build terminé, on indique à Cloud Build que cette image est un "artefact" à sauvegarder.
images:
- 'gcr.io/$PROJECT_ID/cvmatcher-image:$COMMIT_SHA'
