steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/cvmatcher-v2/cvmatcher-repo/cv-matcher-app:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west1-docker.pkg.dev/cvmatcher-v2/cvmatcher-repo/cv-matcher-app:latest' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cv-matcher-service'
      - '--image'
      - 'europe-west1-docker.pkg.dev/cvmatcher-v2/cvmatcher-repo/cv-matcher-app:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'FLASK_ENV=production,GEMINI_API_KEY=AIzaSyBST1NZu1zU-qffOWtoNn6uhzODaJBviiQ,MONGO_URI=mongodb+srv://cvuser:TestPass123@cluster0.blkzqjy.mongodb.net/CVExtraction?retryWrites=true&w=majority&appName=Cluster0'
