services:
  - type: web
    name: cv-matcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: AIzaSyB2w2GCNE6EqvAtcA2Dj9rsvkD2YzFFMfM
        sync: false
      - key: mongodb://localhost:27017
        sync: false
