services:
  - type: web
    name: cv-matcher
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        value: AIzaSyB2w2GCNE6EqvAtcA2Dj9rsvkD2YzFFMfM
      - key: MONGO_URI
        value: mongodb+srv://hugo:lm8HDtRjuwc8LWWb@cluster0.zrj5a8c.mongodb.net/CVExtraction?retryWrites=true&w=majority&appName=Cluster0
