services:
  - type: web
    name: cv-matcher
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        value: AIzaSyB2w2GCNE6EqvAtcA2Dj9rsvkD2YzFFMfM
      - key: MONGO_URI
        value: mongodb+srv://cvapp:CVApp2025@cluster0.zrj5a8c.mongodb.net/CVExtraction?retryWrites=true&w=majority&appName=Cluster0
